##### READ ME ######

#Author: M Almanza

#almanzam@vt.edu


#

#To submit the job do: qsub example1.pbs 
#in the shell

##### END OF README #####


#!/bin/bash

#PBS -m abe

#PBS -M almanzam@vt.edu

#PBS -l walltime=01:00:00

#PBS -e /home/almanzam/projects/ge-detector/out/error/examplePBS.e

#PBS -o /home/almanzam/projects/ge-detector/out/out/examplePBS.o

#PBS -d /home/almanzam/projects/ge-detector/pbs_test

#PBS -D /home/almanzam/

source /home/almanzam/.bashrc.sh

echo "HOST IS " $HOSTNAME

printenv

#actually run the root macro

cd $PBS_O_WORKDIR

/home/almanzam/projects/ge-detector/build/ge-detector /home/almanzam/projects/ge-detector/macros/Copper_cobalt.mac

