/control/verbose 2
/run/verbose 2

/gps/verbose 2

# The activity for this run is 7.26503090634961 kBq
# assuming runtime of 275.291 seconds

#Co-60 (29.47 kBq on September 2008)
#/gps/source/intensity 1
/gps/ion 27 60
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius .25 cm
/gps/pos/halfz .125 cm
/gps/pos/centre 1.25 6.985 23.26 cm
/gps/pos/rot1 0 0 1
/gps/pos/rot2 0 1 0
/gps/ene/type Mono
/gps/ene/mono 0 MeV
/run/beamOn 2000


