/control/verbose 2
/run/verbose 2

/gps/verbose 2

# The activity for this run is 172.32306605 kBq
# assuming runtime of 29.015 seconds

#Co-60( 1 micro Curie on April 2016)
#/gps/source/intensity 1
/gps/ion 55 137
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius .25 cm
/gps/pos/halfz .125 cm
/gps/pos/centre 1.25 -6.985 37.542 cm
/gps/ene/type Mono
/gps/ene/mono 0 MeV
/run/beamOn 5000000 


